### ISSUE TITLE
Is it possible to customize the default location of the subtitles?

### ISSUE THREAD

**Issue by SonicAwareness** [54ac/yt-subtitles#1]
I would like my subtitles to sit higher from the bottom of the screen by default. Moving them around using a mouse in the YouTube interface is clunky and inaccurate. 

Is this possible?

**Comment by 54ac** [comment]
Good idea, I'll look into it.

**Comment by 54ac** [comment]
This option is now available as of version 1.1.5. Let me know if it works.

**Comment by SonicAwareness** [comment]
Wow, thank you for the quick turnaround!

I don't think this is functioning properly. I tried various values with no visible result, all the way to 12.5x just to see if an extreme value would do something.

I attached a video of my test

https://github.com/54ac/yt-subtitles/assets/84392987/e4e7669f-3515-4b7c-a1e1-e85c267f3cac

**Comment by 54ac** [comment]
You're absolutely right, there was a typo in the script that broke everything. I'll publish 1.1.6 soon where it should finally work fine.
