### ISSUE TITLE
Option to center subtitles, change font size to percentages, scale font size to video window size

### ISSUE THREAD

**Issue by bottleblue** [54ac/yt-subtitles#2]
The subtitles are usually off-center in the video. Can we have an option for horizontal centering? The current "text position" center setting is only for vertical position. Manually dragging the subtitles doesn't remember the position between videos.

ex. 
![fullscreen](https://github.com/54ac/yt-subtitles/assets/3678136/033a6915-a8a9-4645-a0c4-ab4b2ca3daf6)

Can we have the font sizes listed in percentages? That would be more intuitive than using a number multiplier. I wanted to pick a font size close to 75%. I had to use trial and error to find out it's 2.4x. 

The font size doesn't scale with the video window size. It's the same whether it's full screen or default view. The font can look too big if the video window is smaller. Youtube's own subtitles does this normally. 

ex. 
![window](https://github.com/54ac/yt-subtitles/assets/3678136/85df33ce-5812-49cb-a78c-271ec3c4e68b) 
![fullscreen](https://github.com/54ac/yt-subtitles/assets/3678136/b5c3dbce-37e0-4ab7-82b9-27bc9bd9e178)

**Comment by 54ac** [comment]
> The subtitles are usually off-center in the video. Can we have an option for horizontal centering? The current "text position" center setting is only for vertical position. Manually dragging the subtitles doesn't remember the position between videos.

They're always centered for me, so I'm not sure what could be causing this. I'll look into it.

> Can we have the font sizes listed in percentages? That would be more intuitive than using a number multiplier. I wanted to pick a font size close to 75%. I had to use trial and error to find out it's 2.4x.

I'll look into this as well. The addon currently uses em units for sizes, but the multipliers indeed don't seem to be very practical.

> The font size doesn't scale with the video window size. It's the same whether it's full screen or default view. The font can look too big if the video window is smaller. Youtube's own subtitles does this normally.

They scale fine for me, I'm not sure why this would happen. Are you using any other addons or scripts that could be interfering with YouTube? Maybe something else is modifying the page and throwing the addon out of whack.

**Comment by bottleblue** [comment]
I use some other youtube addons – Enhancer, Hide Youtube Fullscreen Controls, and Video Resumer. And a couple scripts – Return Youtube Dislike and a script that makes the arrows keys ignore seekbar focus. I disabled all of them but centering doesn't change. 

I did just realize that zooming the page in and out affects the subtitle size, even for text-only zoom. I didn't know that would affect video subtitles. I thought it was just for the web page text. I use Zoom Page WE addon. After disabling that and resetting zoom the scaling seems to work again but only for default view and fullscreen, not theater view. Default view and theater view are the same font size which is annoying since theater is my default window.

I do have a bunch of unrelated addons installed so I'll try experimenting with disabling and see if it helps.

**Comment by 54ac** [comment]
Interesting, thanks for the feedback. I'll look into making the size and centering less fussy.

**Comment by bottleblue** [comment]
I used a new firefox profile with no addons to test youtube's default subtitles. It also has the problem of subtitles not being centered. Sometimes it is. Sometimes it isn't. Maybe it's just a youtube issue. Are your subtitles ALWAYS centered? You've never not had it centered? Especially in theater view?

Theater view is the most annoying because the subtitles are usually to the far left
![111111](https://github.com/54ac/yt-subtitles/assets/3678136/7b943735-7452-4d2b-8bcc-eba4baf927ed)


If you could find a way to make your addon always center the subtitles that would be awesome.

Font scaling works in theater view in a new profile and in my normal profile when I disable Better YT Subtitles but not with it on.

**Comment by bottleblue** [comment]
After messing around some more it seems like the scaling issue is caused by Better YT's font size option and/or the browser's text-only zoom option. If you have font size enabled it appears to "lock" the font size between default view and theater view. 
Likewise with text-only zoom. 

However I tested this on my normal profile. When I created a new profile and only installed Better YT, the font size option still prevented scaling, but the browser's full zoom/text-only zoom option didn't seem to matter. So I'm not entirely sure.

Honestly I don't even care about scaling or centering in default view. I would just like the subtitles to be centered in theater or fullscreen.

**Comment by 54ac** [comment]
I've now added a horizontal/vertical centering option and changed font size to be percentage-based in v1.1.8. This could possibly alleviate your issues, although I personally don't experience them - for me, the subtitles are always centered, including theater mode. I don't use zoom, but it'd stand to reason that the subtitles would get bigger when zoomed in, as they are lines of text after all.

**Comment by bottleblue** [comment]
Nice I'll try it out and let you know. Thx for the quick update!

**Comment by bottleblue** [comment]
Even with the horizontal centering option a lot of videos don't get centered but I think I figured out why. It's because those subtitles are auto-generated. Any subtitles that are auto-generated will look off-centered if the font size is under a certain amount in theater or fullscreen. The smaller the font size the more off-center it is. At 50% font size theater view it's very noticeably uncentered. At 75% theater less so, and at 90% theater it's pretty much centered. However at 90% font size fullscreen it still looks off-centered. It needs to be around 110% font size fullscreen to look centered.

This is with horizontal centering option selected. If it's on default the subtitles never look centered in theater view regardless of font size. 

Subtitles that are not auto-generated will be perfectly centered at any font size. 


Some screenshots:

50% font size theater auto-generated
![50% auto-generated](https://github.com/54ac/yt-subtitles/assets/3678136/e50e62bd-638d-481f-abf0-1348559cc1f7)

75% font size theater auto-generated
![75% auto-generated](https://github.com/54ac/yt-subtitles/assets/3678136/044ef68f-6198-41a7-b44b-403d61fb8c05)

90% font size theater auto-generated
![90% auto-generated theater](https://github.com/54ac/yt-subtitles/assets/3678136/09910836-1a31-4a62-9025-cd642ae2eeb7)

90% font size full-screen auto-generated
![90% auto-generated fullscreen](https://github.com/54ac/yt-subtitles/assets/3678136/075f5cfb-4f71-4f35-ad46-b9077049d321)

Screenshot where subtitles are not auto-generated
50% font size theater view
![50% not auto-generated](https://github.com/54ac/yt-subtitles/assets/3678136/cdb834c3-ae3f-4115-82cd-abe50a504441)


Here's some links to videos that have and don't have auto-generated subtitles if you want to test it out:

Auto-generated
https://www.youtube.com/watch?v=7pMrssIrKcY
https://www.youtube.com/watch?v=WXgQhs4EuQY
https://www.youtube.com/watch?v=OTLfU4ysKHg

Not auto-generated
https://www.youtube.com/watch?v=cDnCgmfhO_U
https://www.youtube.com/watch?v=X8B5ZtKIlWY
https://www.youtube.com/watch?v=dJzkdmJCie4

Who'd have thought centering subtitles could be so complicated huh? 

edit: I get slightly different results when testing on a new profile. 90% font size theater view still looks a little off-center. Also my zoom settings were default on both profiles.

**Comment by 54ac** [comment]
That'd explain it, I don't use auto-generated subtitles at all. I'll look into it.

**Comment by bottleblue** [comment]
If I set youtube's subtitle size to 50% it appears to perfectly center the subtitles in all window modes. I don't remember that doing anything in the last version but maybe something changed in the update.  The font won't scale though so in theater mode the font's slightly too big and in fullscreen it's slightly too small but this is a decent workaround.

**Comment by 54ac** [comment]
Yes, auto-generated subtitles are not perfectly centered because they're left-aligned in a big box so that the words don't jump around when they pop in, that's by design. Centering would make the previous words move to the left when new ones appear, making them annoying to read.

**Comment by bottleblue** [comment]
I see. This workaround I'm using makes it pretty well centered so I feel like Youtube could have tweaked it a bit and made it less left-aligned. Oh well. If nothing more can be done I guess I'll just use this method.

**Comment by 54ac** [comment]
Yeah, I feel like they could have made the box a bit smaller, but I don't really want to mess with that.

**Comment by bottleblue** [comment]
Totally understand. It's still a good addon regardless. Thx for taking the time to look into this. It was much appreciated!
